name: Deploy to ECS Fargate with Blue/Green

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  ECR_REPO: parth-strapi-ecr
  ECR_ACCOUNT: 607700977843
  ECS_CLUSTER: parth-strapi-cluster
  ECS_SERVICE: parth-strapi-service
  TASK_FAMILY: parth-strapi-task
  DEPLOYMENT_GROUP: parth-dg
  CODEDEPLOY_APP: parth-strapi-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Ensure ECR Repo Exists
      run: |
        aws ecr describe-repositories --repository-names $ECR_REPO || \
        aws ecr create-repository --repository-name $ECR_REPO

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build & Push Docker image with GitHub SHA Tag
      run: |
        IMAGE_TAG=${{ github.sha }}
        ECR_URI=${{ env.ECR_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}
        docker build -t $ECR_URI:$IMAGE_TAG ./strapi-app
        docker push $ECR_URI:$IMAGE_TAG
        echo "IMAGE_URI=$ECR_URI:$IMAGE_TAG" >> $GITHUB_ENV

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Apply with Dynamic Image URL
      working-directory: terraform
      run: terraform apply -auto-approve -var="ecr_image_url=${{ env.IMAGE_URI }}"

    - name: Wait and Fetch New Task Definition ARN
      id: taskdef
      run: |
        echo "Fetching Task Definition ARN..."
        for i in {1..10}; do
          TASK_DEF_ARN=$(aws ecs describe-task-definition --task-definition $TASK_FAMILY --query "taskDefinition.taskDefinitionArn" --output text || echo "None")
          echo "Attempt $i: $TASK_DEF_ARN"
          if [[ "$TASK_DEF_ARN" != "None" ]]; then
            echo "Found Task Definition ARN: $TASK_DEF_ARN"
            echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV
            echo "::set-output name=task_def_arn::$TASK_DEF_ARN"
            break
          fi
          echo "Task Definition not available yet. Retrying in 10s..."
          sleep 10
        done

        if [[ "$TASK_DEF_ARN" == "None" ]]; then
          echo "Failed to fetch Task Definition ARN after retries."
          exit 1
        fi

    - name: Replace Task ARN in AppSpec YAML
      run: |
        sed -i "s|REPLACE_TASK_DEFINITION_ARN|${{ steps.taskdef.outputs.task_def_arn }}|g" appspec.yaml
        cat appspec.yaml

    - name: Deploy with CodeDeploy (YAML Inline)
      run: |
        BASE64_CONTENT=$(base64 -w 0 appspec.yaml)
        aws deploy create-deployment \
          --application-name $CODEDEPLOY_APP \
          --deployment-group-name $DEPLOYMENT_GROUP \
          --revision revisionType=AppSpecContent,appSpecContent="{content=$BASE64_CONTENT}" \
          --deployment-config-name CodeDeployDefault.ECSCanary10Percent5Minutes \
          --region $AWS_REGION

    - name: Monitor Deployment Status
      run: |
        DEPLOYMENT_ID=$(aws deploy list-deployments --application-name $CODEDEPLOY_APP --deployment-group-name $DEPLOYMENT_GROUP --query 'deployments[0]' --output text)
        echo "Deployment ID: $DEPLOYMENT_ID"

        STATUS="InProgress"
        while [ "$STATUS" == "InProgress" ]; do
          STATUS=$(aws deploy get-deployment --deployment-id $DEPLOYMENT_ID --query 'deploymentInfo.status' --output text)
          echo "Current Deployment Status: $STATUS"
          sleep 15
        done

        if [ "$STATUS" != "Succeeded" ]; then
          echo "Deployment Failed! Exiting..."
          exit 1
        fi
