name: Force Delete AWS Resources

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  CLUSTER_NAME: parth-strapi-cluster
  SERVICE_NAME: parth-strapi-service
  TASK_FAMILY: parth-strapi-task
  TG_BLUE: parth-strapi-tg-blue
  TG_GREEN: parth-strapi-tg-green
  ALB_NAME: parth-strapi-alb
  ECR_REPO: parth-strapi-ecr

jobs:
  force-delete:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Stop & delete ECS service & cluster
      run: |
        aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --desired-count 0 || true
        sleep 15
        aws ecs delete-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force || true
        aws ecs delete-cluster --cluster $CLUSTER_NAME || true

    - name: Deregister task definitions
      run: |
        for arn in $(aws ecs list-task-definitions --family-prefix $TASK_FAMILY --output text); do
          aws ecs deregister-task-definition --task-definition "$arn" || true
        done

    - name: Delete ALB, target groups
      run: |
        #-clean deletes with safeguards

    - name: Delete SGs and ECR
      run: |
        #-clean logic as before
