name: Destroy All Strapi Infra

on:
  workflow_dispatch:  # manual trigger only

env:
  AWS_REGION: us-east-2

jobs:
  destroy:
    name: Destroy All AWS Infra
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Destroy (forcefully delete all)
      working-directory: terraform
      run: terraform destroy -auto-approve -var="607700977843.dkr.ecr.us-east-2.amazonaws.com/parth-strapi-ecr:parth-strapi-1754080549"
